/**
 * `slotsmith-ai add`
 *
 * Copies a ready-made adapter into a project as source the user owns. The
 * adapters are the ones generated from the tested integration skins; the
 * command only places them, prints how to use them, and names the packages
 * still to install. It never installs anything itself.
 *
 * @packageDocumentation
 */

import { existsSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import packageJson from "../../package.json";
import { adaptersFor, loadKnowledge, type Knowledge } from "../knowledge/load";
import type { AdapterRef, ComponentName, Library } from "../knowledge/types";
import { ADD_USAGE, parseAddArgs } from "./args";
import { resolveInside, writeFileSafely, type WriteResult } from "./write";

/**
 * CLI I/O
 *
 * Where a command runs and where it prints. Each call to `out` or `err` is
 * one or more whole lines, without the trailing newline.
 */
export interface CliIo {
  /** The project folder; every path is resolved against it and must stay inside it. */
  cwd: string;
  /** Normal output. */
  out: (text: string) => void;
  /** Errors and refusals. */
  err: (text: string) => void;
}

/**
 * Library setup
 *
 * What a library needs beyond the packages an adapter imports: the packages
 * it expects to find next to its components, and any one-time setup in the
 * app. The index lists only an adapter's direct imports, so these are added
 * here.
 */
const LIBRARY_SETUP: Readonly<Record<Library, { packages: string[]; note?: string }>> = {
  mui: { packages: ["@emotion/react", "@emotion/styled"] },
  chakra: { packages: ["@emotion/react"] },
  antd: { packages: [] },
  shadcn: { packages: [] },
  radix: {
    packages: [],
    note: 'Radix Themes needs its stylesheet and a theme root: import "@radix-ui/themes/styles.css" once and wrap the app in <Theme>.',
  },
};

/**
 * Header
 *
 * @param library - The library.
 * @param component - The component.
 * @returns The comment line every added file starts with.
 */
const header = (library: Library, component: ComponentName): string =>
  `// slotsmith ${library} adapter for ${component}, generated by slotsmith-ai ${packageJson.version}. This file is yours to edit.`;

/**
 * Project packages
 *
 * @param cwd - The project folder.
 * @returns Every package its `package.json` already lists; empty when there is none or it cannot be read.
 */
function projectPackages(cwd: string): Set<string> {
  const manifest = join(cwd, "package.json");
  if (!existsSync(manifest)) return new Set();
  try {
    const json = JSON.parse(readFileSync(manifest, "utf8")) as Record<string, unknown>;
    const names = ["dependencies", "devDependencies", "peerDependencies"].flatMap((field) => {
      const deps = json[field];
      return deps && typeof deps === "object" ? Object.keys(deps) : [];
    });
    return new Set(names);
  } catch {
    return new Set();
  }
}

/**
 * Import specifier
 *
 * The module path an app imports the adapter from, through the usual `@/`
 * alias for the source root (`src/` when the file is under it, else the
 * project root).
 *
 * @param cwd - The project folder.
 * @param file - The adapter's absolute path.
 * @returns E.g. `@/components/slotsmith/date-picker`.
 */
function importSpecifier(cwd: string, file: string): string {
  const rel = relative(cwd, file).replace(/\\/g, "/").replace(/\.tsx$/, "");
  return `@/${rel.replace(/^src\//, "")}`;
}

/**
 * shadcn components
 *
 * @param source - An adapter's source.
 * @returns The `@/components/ui/*` modules it imports, which the app adds with the shadcn CLI.
 */
const shadcnComponents = (source: string): string[] =>
  [...source.matchAll(/from\s+["']@\/components\/ui\/([\w-]+)["']/g)].map((match) => match[1]!);

/**
 * Describe result
 *
 * @param result - A write result.
 * @param shown - The path as the user should read it.
 * @returns One line for the result.
 */
function describeResult(result: WriteResult, shown: string): string {
  const differs = (count = 0) => `${count} line${count === 1 ? "" : "s"} differ${count === 1 ? "s" : ""}`;
  switch (result.status) {
    case "created":
      return `created ${shown}`;
    case "unchanged":
      return `unchanged ${shown}`;
    case "overwritten":
      return `overwritten ${shown} (${differs(result.changedLines)})`;
    case "would-create":
      return `would create ${shown}`;
    case "would-overwrite":
      return `would overwrite ${shown} (${differs(result.changedLines)}; without --force it would be left as is)`;
    case "refused":
      return `refused ${shown}: it has been edited (${differs(result.changedLines)} from the adapter). It was left as is; run again with --force to replace it.`;
  }
}

/**
 * Run add
 *
 * @param argv - The arguments after `add`.
 * @param io - Where to run and print.
 * @param knowledge - The knowledge to take the adapters from. Defaults to the generated one.
 * @returns The exit code: `0` when every file was created, unchanged or overwritten (or would be), `1` otherwise.
 */
export async function runAdd(argv: string[], io: CliIo, knowledge?: Knowledge): Promise<number> {
  const parsed = parseAddArgs(argv);
  if (!parsed.ok) {
    io.err(`${parsed.error}\n\n${ADD_USAGE}`);
    return 1;
  }
  if ("help" in parsed) {
    io.out(ADD_USAGE);
    return 0;
  }
  const { components, library, out, force, dryRun } = parsed.args;

  const outDir = out ?? (existsSync(join(io.cwd, "src")) ? "src/components/slotsmith" : "components/slotsmith");
  const outPath = resolveInside(io.cwd, outDir);
  if (!outPath) {
    io.err(`--out "${outDir}" is outside the project (${io.cwd}). Give a folder inside it.`);
    return 1;
  }

  const known = knowledge ?? loadKnowledge();
  const plan: { component: ComponentName; adapter: AdapterRef; source: string; exportName: string; file: string }[] = [];
  for (const component of components) {
    const adapter = adaptersFor(known, component).find((entry) => entry.library === library);
    const source = adapter && known.adapters.get(adapter.file);
    const exportName = known.components.get(component)?.exportName;
    if (!adapter || source === undefined || !exportName) {
      io.err(`No ${library} adapter for ${component} in slotsmith-ai ${packageJson.version}.`);
      return 1;
    }
    plan.push({ component, adapter, source, exportName, file: join(outPath, `${component}.tsx`) });
  }

  let refused = false;
  let placed = 0;
  const peers: string[] = [];
  const shadcn: string[] = [];
  for (const { component, adapter, source, exportName, file } of plan) {
    const content = `${header(library, component)}\n${source.endsWith("\n") ? source : `${source}\n`}`;
    const result = writeFileSafely(file, content, { force, dryRun });
    const shown = relative(io.cwd, file).replace(/\\/g, "/");
    if (result.status === "refused") {
      refused = true;
      io.err(describeResult(result, shown));
      continue;
    }

    placed += 1;
    const mapName = `${library}${exportName}`;
    io.out(
      [
        describeResult(result, shown),
        `  import { ${mapName} } from "${importSpecifier(io.cwd, file)}";`,
        `  <${exportName} components={${mapName}} />`,
      ].join("\n"),
    );
    peers.push(...adapter.peers);
    shadcn.push(...shadcnComponents(source));
  }

  if (placed > 0) {
    const installed = projectPackages(io.cwd);
    const wanted = [...new Set(["slotsmith", ...peers, ...LIBRARY_SETUP[library].packages])];
    const missing = wanted.filter((name) => !installed.has(name));
    const lines: string[] = [];
    if (missing.length > 0) lines.push("", "Install what the project is missing:", `npm install ${missing.join(" ")}`);
    if (shadcn.length > 0) lines.push("", "Add the shadcn/ui components it uses:", `npx shadcn@latest add ${[...new Set(shadcn)].sort().join(" ")}`);
    const note = LIBRARY_SETUP[library].note;
    if (note) lines.push("", note);
    if (lines.length > 0) io.out(lines.join("\n"));
  }

  return refused ? 1 : 0;
}
