import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import packageJson from "../../../package.json";
import { runAdd } from "../add";

const dirs: string[] = [];

afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

/**
 * Project
 *
 * A fresh temporary project folder.
 *
 * @param options - Whether it has `src/`, and the `package.json` to write, if any.
 * @returns Its absolute path.
 */
function project(options: { src?: boolean; manifest?: object } = {}): string {
  const dir = mkdtempSync(join(tmpdir(), "slotsmith-add-"));
  dirs.push(dir);
  if (options.src !== false) mkdirSync(join(dir, "src"));
  if (options.manifest) writeFileSync(join(dir, "package.json"), JSON.stringify(options.manifest));
  return dir;
}

/**
 * Add
 *
 * Runs the command in a project and collects what it prints.
 *
 * @param cwd - The project.
 * @param argv - The arguments after `add`.
 * @returns The exit code and the output, joined.
 */
async function add(cwd: string, ...argv: string[]) {
  const out: string[] = [];
  const err: string[] = [];
  const code = await runAdd(argv, { cwd, out: (text) => out.push(text), err: (text) => err.push(text) });
  return { code, out: out.join("\n"), err: err.join("\n"), all: [...out, ...err].join("\n") };
}

/**
 * Files under
 *
 * @param dir - A folder.
 * @returns Every file below it, relative and with forward slashes, sorted.
 */
function filesUnder(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return (readdirSync(dir, { recursive: true, withFileTypes: true }) as import("node:fs").Dirent[])
    .filter((entry) => entry.isFile())
    .map((entry) => join(entry.parentPath, entry.name).slice(dir.length + 1).replace(/\\/g, "/"))
    .sort();
}

const HEADER = `// slotsmith mui adapter for date-picker, generated by slotsmith-ai ${packageJson.version}. This file is yours to edit.`;

describe("slotsmith-ai add", () => {
  it("writes the adapter under src/components/slotsmith when src/ exists", async () => {
    const cwd = project();
    const result = await add(cwd, "date-picker", "--ui", "mui");
    expect(result.code).toBe(0);
    const file = join(cwd, "src/components/slotsmith/date-picker.tsx");
    const content = readFileSync(file, "utf8");
    expect(content.startsWith(`${HEADER}\n`)).toBe(true);
    expect(content).toContain("muiDatePicker");
    expect(result.out).toContain("src/components/slotsmith/date-picker.tsx");
    expect(result.out).toContain('import { muiDatePicker } from "@/components/slotsmith/date-picker";');
    expect(result.out).toContain("<DatePicker components={muiDatePicker} />");
  });

  it("writes under components/slotsmith when there is no src/", async () => {
    const cwd = project({ src: false });
    expect((await add(cwd, "date-picker", "--ui", "mui")).code).toBe(0);
    expect(filesUnder(cwd)).toEqual(["components/slotsmith/date-picker.tsx"]);
  });

  it("writes to --out", async () => {
    const cwd = project();
    const result = await add(cwd, "date-picker", "--ui", "mui", "--out", "src/ui/x");
    expect(result.code).toBe(0);
    expect(filesUnder(cwd)).toEqual(["src/ui/x/date-picker.tsx"]);
    expect(result.out).toContain('from "@/ui/x/date-picker"');
  });

  it("reports unchanged on a second run", async () => {
    const cwd = project();
    const file = join(cwd, "src/components/slotsmith/date-picker.tsx");
    await add(cwd, "date-picker", "--ui", "mui");
    const before = readFileSync(file);
    const second = await add(cwd, "date-picker", "--ui", "mui");
    expect(second.code).toBe(0);
    expect(second.out).toMatch(/unchanged/);
    expect(readFileSync(file).equals(before)).toBe(true);
  });

  it("refuses to replace a file the user edited", async () => {
    const cwd = project();
    const file = join(cwd, "src/components/slotsmith/date-picker.tsx");
    await add(cwd, "date-picker", "--ui", "mui");
    appendFileSync(file, "// edited\n");
    const edited = readFileSync(file, "utf8");

    const result = await add(cwd, "date-picker", "--ui", "mui");
    expect(result.code).toBe(1);
    expect(readFileSync(file, "utf8")).toBe(edited);
    expect(result.all).toContain("src/components/slotsmith/date-picker.tsx");
    expect(result.all).toMatch(/1 line differs/);
    expect(result.all).toContain("--force");
  });

  it("replaces an edited file with --force", async () => {
    const cwd = project();
    const file = join(cwd, "src/components/slotsmith/date-picker.tsx");
    await add(cwd, "date-picker", "--ui", "mui");
    const original = readFileSync(file, "utf8");
    appendFileSync(file, "// edited\n");

    const result = await add(cwd, "date-picker", "--ui", "mui", "--force");
    expect(result.code).toBe(0);
    expect(result.out).toMatch(/overwritten/);
    expect(readFileSync(file, "utf8")).toBe(original);
  });

  it("treats an untouched file from an older slotsmith-ai as unchanged", async () => {
    const cwd = project();
    const file = join(cwd, "src/components/slotsmith/date-picker.tsx");
    await add(cwd, "date-picker", "--ui", "mui");
    const older = readFileSync(file, "utf8").replace(`slotsmith-ai ${packageJson.version}.`, "slotsmith-ai 1.0.0.");
    writeFileSync(file, older);

    const result = await add(cwd, "date-picker", "--ui", "mui");
    expect(result.code).toBe(0);
    expect(result.out).toMatch(/unchanged/);
    expect(readFileSync(file, "utf8")).toBe(older);
  });

  it("still refuses an edited file from an older slotsmith-ai", async () => {
    const cwd = project();
    const file = join(cwd, "src/components/slotsmith/date-picker.tsx");
    await add(cwd, "date-picker", "--ui", "mui");
    const older = `${readFileSync(file, "utf8").replace(`slotsmith-ai ${packageJson.version}.`, "slotsmith-ai 1.0.0.")}// edited\n`;
    writeFileSync(file, older);

    const result = await add(cwd, "date-picker", "--ui", "mui");
    expect(result.code).toBe(1);
    expect(result.all).toContain(`differs from the adapter slotsmith-ai ${packageJson.version} would write (1 line differs; pass --force to replace)`);
    expect(readFileSync(file, "utf8")).toBe(older);
  });

  it("predicts the refusal on --dry-run", async () => {
    const cwd = project();
    const file = join(cwd, "src/components/slotsmith/date-picker.tsx");
    await add(cwd, "date-picker", "--ui", "mui");
    appendFileSync(file, "// edited\n");
    const edited = readFileSync(file, "utf8");

    const result = await add(cwd, "date-picker", "--ui", "mui", "--dry-run");
    expect(result.code).toBe(1);
    expect(result.all).toMatch(/would refuse src\/components\/slotsmith\/date-picker\.tsx/);
    expect(result.all).toContain("--force");
    expect(readFileSync(file, "utf8")).toBe(edited);

    const forced = await add(cwd, "date-picker", "--ui", "mui", "--dry-run", "--force");
    expect(forced.code).toBe(0);
    expect(forced.out).toMatch(/would overwrite src\/components\/slotsmith\/date-picker\.tsx \(1 line differs\)/);
    expect(forced.all).not.toContain("left as is");
    expect(readFileSync(file, "utf8")).toBe(edited);
  });

  it("refuses an --out that leads outside through a junction", async (context) => {
    const cwd = project();
    const outside = project({ src: false });
    try {
      symlinkSync(outside, join(cwd, "src", "link"), "junction");
    } catch {
      context.skip();
    }
    const result = await add(cwd, "date-picker", "--ui", "mui", "--out", "src/link/slotsmith");
    expect(result.code).toBe(1);
    expect(result.all).toMatch(/outside the project/);
    expect(filesUnder(outside)).toEqual([]);
  });

  it("refuses to write through a file that is a symbolic link", async (context) => {
    const cwd = project();
    const outside = project({ src: false });
    const target = join(outside, "target.tsx");
    writeFileSync(target, "// someone else's file\n");
    mkdirSync(join(cwd, "src/components/slotsmith"), { recursive: true });
    try {
      symlinkSync(target, join(cwd, "src/components/slotsmith/date-picker.tsx"), "file");
    } catch {
      context.skip();
    }
    const result = await add(cwd, "date-picker", "--ui", "mui", "--force");
    expect(result.code).toBe(1);
    expect(result.all).toMatch(/refused src\/components\/slotsmith\/date-picker\.tsx: it is a link/);
    expect(readFileSync(target, "utf8")).toBe("// someone else's file\n");
  });

  it("writes nothing on --dry-run", async () => {
    const cwd = project();
    const result = await add(cwd, "date-picker", "--ui", "mui", "--dry-run");
    expect(result.code).toBe(0);
    expect(filesUnder(cwd)).toEqual([]);
    expect(result.out).toMatch(/would create .*src\/components\/slotsmith\/date-picker\.tsx/);
  });

  it("accepts ant-design for antd", async () => {
    const alias = project();
    const canonical = project();
    expect((await add(alias, "data-table", "--ui", "ant-design")).code).toBe(0);
    expect((await add(canonical, "data-table", "--ui", "antd")).code).toBe(0);
    const read = (cwd: string) => readFileSync(join(cwd, "src/components/slotsmith/data-table.tsx"), "utf8");
    expect(read(alias)).toBe(read(canonical));
    expect(read(alias)).toContain("antdDataTable");
  });

  it("accepts radix-themes for radix", async () => {
    const alias = project();
    const canonical = project();
    const result = await add(alias, "autocomplete", "--ui", "radix-themes");
    expect(result.code).toBe(0);
    expect((await add(canonical, "autocomplete", "--ui", "radix")).code).toBe(0);
    const read = (cwd: string) => readFileSync(join(cwd, "src/components/slotsmith/autocomplete.tsx"), "utf8");
    expect(read(alias)).toBe(read(canonical));
    expect(read(alias)).toContain('from "@radix-ui/themes"');
    expect(result.out).toContain("@radix-ui/themes/styles.css");
    expect(result.out).toContain("<Theme>");
  });

  it.each([
    ["an unknown library", ["date-picker", "--ui", "bootstrap"], ["mui", "shadcn", "chakra", "antd", "radix"]],
    ["a missing --ui", ["date-picker"], ["mui", "shadcn", "chakra", "antd", "radix"]],
    ["an unknown component", ["date-pickr", "--ui", "mui"], ["data-table", "autocomplete", "file-uploader", "date-picker"]],
    ["no component", ["--ui", "mui"], ["data-table", "autocomplete", "file-uploader", "date-picker"]],
    ["an unknown option", ["date-picker", "--ui", "mui", "--frobnicate"], ["--frobnicate"]],
  ])("rejects %s", async (_, argv, expected) => {
    const cwd = project();
    const result = await add(cwd, ...argv);
    expect(result.code).toBe(1);
    for (const value of expected) expect(result.all).toContain(value);
    expect(filesUnder(cwd)).toEqual([]);
  });

  it("writes every component with --all", async () => {
    const cwd = project();
    expect((await add(cwd, "--all", "--ui", "chakra")).code).toBe(0);
    expect(filesUnder(cwd)).toEqual([
      "src/components/slotsmith/autocomplete.tsx",
      "src/components/slotsmith/data-table.tsx",
      "src/components/slotsmith/date-picker.tsx",
      "src/components/slotsmith/file-uploader.tsx",
    ]);
  });

  it("writes several named components", async () => {
    const cwd = project();
    const result = await add(cwd, "data-table", "date-picker", "--ui", "mui");
    expect(result.code).toBe(0);
    expect(filesUnder(cwd)).toEqual(["src/components/slotsmith/data-table.tsx", "src/components/slotsmith/date-picker.tsx"]);
    expect(result.out).toContain("<DataTable components={muiDataTable} />");
    expect(result.out).toContain("<DatePicker components={muiDatePicker} />");
  });

  it.each([["../outside"], ["..\\outside"], ["src/../../outside"]])("refuses --out %s", async (out) => {
    const cwd = project();
    const result = await add(cwd, "date-picker", "--ui", "mui", "--out", out);
    expect(result.code).toBe(1);
    expect(result.all).toMatch(/outside the project/);
    expect(filesUnder(cwd)).toEqual([]);
    expect(existsSync(join(cwd, "..", "outside"))).toBe(false);
  });

  it("refuses an absolute --out elsewhere", async () => {
    const cwd = project();
    const elsewhere = project();
    const result = await add(cwd, "date-picker", "--ui", "mui", "--out", elsewhere);
    expect(result.code).toBe(1);
    expect(filesUnder(cwd)).toEqual([]);
    expect(filesUnder(elsewhere)).toEqual([]);
  });

  it("names only the direct peers the project is missing", async () => {
    const cwd = project({ manifest: { dependencies: { slotsmith: "^1.6.0", antd: "^5.0.0" } } });
    const result = await add(cwd, "date-picker", "--ui", "antd");
    expect(result.out).toMatch(/^npm install @ant-design\/icons$/m);
  });

  it("adds the setup packages a library needs next to its components", async () => {
    const cwd = project({
      manifest: { dependencies: { slotsmith: "^1.6.0", "@mui/material": "^7.0.0" }, devDependencies: { "@emotion/react": "^11.0.0" } },
    });
    const result = await add(cwd, "date-picker", "--ui", "mui");
    expect(result.out).toMatch(/^npm install @emotion\/styled$/m);
  });

  it("prints no install line when nothing is missing", async () => {
    const cwd = project({ manifest: { dependencies: { slotsmith: "1", "@chakra-ui/react": "3", "@emotion/react": "11" } } });
    const result = await add(cwd, "date-picker", "--ui", "chakra");
    expect(result.code).toBe(0);
    expect(result.out).not.toContain("npm install");
  });

  it("names every package when the project has no package.json", async () => {
    const cwd = project();
    const result = await add(cwd, "date-picker", "--ui", "mui");
    expect(result.code).toBe(0);
    expect(result.out).toMatch(/^npm install slotsmith @mui\/material @emotion\/react @emotion\/styled$/m);
  });

  it("does not crash on an unreadable package.json", async () => {
    const cwd = project();
    writeFileSync(join(cwd, "package.json"), "{ not json");
    const result = await add(cwd, "date-picker", "--ui", "mui");
    expect(result.code).toBe(0);
    expect(result.out).toContain("npm install slotsmith @mui/material");
  });

  it("lists the shadcn components an adapter imports", async () => {
    const cwd = project({ manifest: { dependencies: { slotsmith: "1" } } });
    const result = await add(cwd, "autocomplete", "data-table", "--ui", "shadcn");
    expect(result.code).toBe(0);
    expect(result.out).toMatch(/^npx shadcn@latest add badge button checkbox input select separator skeleton table$/m);
    expect(result.out).not.toMatch(/^npm install/m);
  });
});
