/**
 * shadcn registry
 *
 * Publishes the shadcn adapters as a shadcn/ui registry: one item per
 * component, plus the top-level `registry.json` index next to them. Both are read from the knowledge `generate.ts`
 * already wrote — `knowledge/index.json` for the adapter list and their peers,
 * `knowledge/adapters/*.tsx` for the source itself — so nothing here parses
 * the library a second time.
 *
 * The item's file path matches what `slotsmith-ai add --ui shadcn` writes
 * (`components/slotsmith/<component>.tsx`), so shadcn's own CLI and this
 * package's CLI place the adapter at the same spot in a project. The `add`
 * command's header line ("generated by slotsmith-ai X.Y.Z…") names a tool
 * shadcn's CLI never runs, so it is left out of the registry content.
 *
 * The two routes do not end up byte-for-byte identical, though: shadcn's
 * own CLI strips a file's leading doc comment when it installs a
 * `registry:component` (confirmed against the real CLI), so a file it
 * places is missing the adapter's introductory comment that
 * `knowledge/adapters/` keeps. Run `slotsmith-ai add` over such a file
 * afterward and it reports the file as differing (the missing comment) and
 * refuses without `--force` — the same as any other hand-edited file.
 *
 * Nothing under `registry/` is written by hand: run with
 * `node scripts/registry.ts` (or `pnpm registry`); it also runs at the end
 * of `pnpm build`.
 *
 * @packageDocumentation
 */

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { KnowledgeIndex } from "../src/knowledge/types.ts";
import { PACKAGE_ROOT } from "./generate.ts";

/** One file a registry item installs, inlined so the item is servable on its own. */
export interface RegistryItemFile {
  /** The file's path relative to the registry root, kept the same shape as `target` for readability. */
  path: string;
  /** Always `registry:component`: a plain source file. */
  type: "registry:component";
  /**
   * Where shadcn's CLI actually writes the file, via the `@components/`
   * alias placeholder. Required in practice, not just in the schema's
   * `registry:file`/`registry:page` branch: without it, the CLI resolves a
   * `registry:component` file to `<components alias>/<basename>` and drops
   * every subfolder in `path`, which would land the adapter one level up
   * from where `slotsmith-ai add` puts it (confirmed against the real CLI
   * in a scratch project — see the task's hand-over notes).
   */
  target: string;
  /**
   * The adapter's source, exactly as `knowledge/adapters/` holds it: the
   * component's own doc comment, but none of the `// slotsmith … generated
   * by slotsmith-ai X.Y.Z …` header `slotsmith-ai add` prepends when it
   * writes the file — that header names a tool shadcn's own CLI never runs.
   */
  content: string;
}

/** A single component's registry item: `packages/ai/registry/<component>.json`. */
export interface RegistryItem {
  $schema: "https://ui.shadcn.com/schema/registry-item.json";
  /** Unique in the registry: `slotsmith-<component>`. */
  name: string;
  type: "registry:component";
  /** `slotsmith <component title, lowercase>`, e.g. "slotsmith date picker". */
  title: string;
  /** One sentence: what this item is. */
  description: string;
  /** `["slotsmith", ...the adapter's peers]`, e.g. `["slotsmith", "@mui/material"]`. */
  dependencies: string[];
  /** The `@/components/ui/<name>` imports the adapter makes, sorted. */
  registryDependencies: string[];
  files: [RegistryItemFile];
}

/** The index, `packages/ai/registry/registry.json`, listing every item without their file content. */
export interface RegistryIndex {
  $schema: "https://ui.shadcn.com/schema/registry.json";
  name: string;
  homepage: string;
  items: {
    name: string;
    type: "registry:component";
    title: string;
    description: string;
    dependencies: string[];
    registryDependencies: string[];
    files: { path: string; type: "registry:component"; target: string }[];
  }[];
}

const ITEM_SCHEMA = "https://ui.shadcn.com/schema/registry-item.json" as const;
const INDEX_SCHEMA = "https://ui.shadcn.com/schema/registry.json" as const;

/**
 * shadcn components
 *
 * @param source - An adapter's source.
 * @returns The `@/components/ui/*` modules it imports, sorted, matching what `slotsmith-ai add` tells the user to install.
 */
function shadcnComponents(source: string): string[] {
  const names = [...source.matchAll(/from\s+["']@\/components\/ui\/([\w-]+)["']/g)].map((match) => match[1]!);
  return [...new Set(names)].sort();
}

/**
 * Build registry items
 *
 * @param index - The generated knowledge index.
 * @param adapters - Each shadcn adapter's source, by file name (`knowledge/adapters/<file>`).
 * @returns One item per component, in the index's adapter order (alphabetical by file name, so by component).
 */
export function buildRegistryItems(index: KnowledgeIndex, adapters: Map<string, string>): RegistryItem[] {
  return index.adapters
    .filter((adapter) => adapter.library === "shadcn")
    .map((adapter): RegistryItem => {
      const source = adapters.get(adapter.file);
      if (source === undefined) throw new Error(`no adapter source loaded for ${adapter.file}`);
      const summary = index.components.find((component) => component.name === adapter.component);
      if (!summary) throw new Error(`${adapter.component} is not in the knowledge index`);
      const title = summary.title.toLowerCase();
      return {
        $schema: ITEM_SCHEMA,
        name: `slotsmith-${adapter.component}`,
        type: "registry:component",
        title: `slotsmith ${title}`,
        description: `shadcn parts for the slotsmith ${title}.`,
        dependencies: ["slotsmith", ...adapter.peers],
        registryDependencies: shadcnComponents(source),
        files: [
          {
            path: `components/slotsmith/${adapter.component}.tsx`,
            type: "registry:component",
            target: `@components/slotsmith/${adapter.component}.tsx`,
            content: source,
          },
        ],
      };
    });
}

/**
 * Build registry index
 *
 * @param items - The registry items.
 * @param options - The registry's own name and homepage.
 * @returns The top-level `registry.json`, with each item's file content left out: the index is a catalog, and the content is already served at `/r/<component>.json`.
 */
export function buildRegistryIndex(items: RegistryItem[], options: { name: string; homepage: string }): RegistryIndex {
  return {
    $schema: INDEX_SCHEMA,
    name: options.name,
    homepage: options.homepage,
    items: items.map((item) => ({
      name: item.name,
      type: item.type,
      title: item.title,
      description: item.description,
      dependencies: item.dependencies,
      registryDependencies: item.registryDependencies,
      files: item.files.map((file) => ({ path: file.path, type: file.type, target: file.target })),
    })),
  };
}

/**
 * Registry options
 */
export interface RegistryOptions {
  /** `knowledge/`, already written by `generate.ts`. */
  knowledgeDir: string;
  /** Where to write `<component>.json` and `registry.json`. */
  outDir: string;
  /** The registry's own name, in `registry.json`. */
  registryName: string;
  /** The registry's own homepage, in `registry.json`. */
  homepage: string;
}

/** The default options: this package's knowledge and registry folders. */
export const DEFAULT_REGISTRY_OPTIONS: RegistryOptions = {
  knowledgeDir: join(PACKAGE_ROOT, "knowledge"),
  outDir: join(PACKAGE_ROOT, "registry"),
  registryName: "slotsmith",
  homepage: "https://slotsmith.dev",
};

/**
 * Load shadcn adapters
 *
 * @param knowledgeDir - `knowledge/`.
 * @param index - The generated knowledge index.
 * @returns Every shadcn adapter's source, by its file name under `knowledge/adapters/`.
 */
function loadShadcnAdapters(knowledgeDir: string, index: KnowledgeIndex): Map<string, string> {
  const adapters = new Map<string, string>();
  for (const adapter of index.adapters) {
    if (adapter.library !== "shadcn") continue;
    adapters.set(adapter.file, readFileSync(join(knowledgeDir, "adapters", adapter.file), "utf8"));
  }
  return adapters;
}

/**
 * Write registry
 *
 * Reads the already-generated knowledge and writes the shadcn registry:
 * one JSON file per component and the top-level index. The folder is
 * emptied first, so a component or adapter that no longer exists leaves no
 * stale file behind.
 *
 * @param options - Where the knowledge lives and the registry is written.
 * @returns The items and the index, in memory.
 */
export function writeRegistry(options: RegistryOptions = DEFAULT_REGISTRY_OPTIONS): { items: RegistryItem[]; index: RegistryIndex } {
  const knowledgeIndex = JSON.parse(readFileSync(join(options.knowledgeDir, "index.json"), "utf8")) as KnowledgeIndex;
  const adapters = loadShadcnAdapters(options.knowledgeDir, knowledgeIndex);
  const items = buildRegistryItems(knowledgeIndex, adapters);
  const index = buildRegistryIndex(items, { name: options.registryName, homepage: options.homepage });

  rmSync(options.outDir, { recursive: true, force: true });
  mkdirSync(options.outDir, { recursive: true });
  for (const item of items) {
    const component = item.name.replace(/^slotsmith-/, "");
    writeFileSync(join(options.outDir, `${component}.json`), `${JSON.stringify(item, null, 2)}\n`);
  }
  writeFileSync(join(options.outDir, "registry.json"), `${JSON.stringify(index, null, 2)}\n`);
  return { items, index };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { items } = writeRegistry();
  process.stdout.write(`Wrote the shadcn registry: ${items.map((item) => item.name.replace(/^slotsmith-/, "")).join(", ")}.\n`);
}
