/** Old hash-route slug (after `#/docs/`) to the new path. The empty key is the old home, `#/`. */
export const HASH_ROUTES: Record<string, string> = {
  "": "/",
  installation: "/getting-started/",
  slots: "/guides/",
  theming: "/theming/",
  locales: "/languages/",
  "ai-tools": "/ai-tools/",
  "data-table": "/components/data-table/",
  "file-uploader": "/components/file-uploader/",
  autocomplete: "/components/autocomplete/",
  "date-picker": "/components/date-picker/",
  author: "/about/",
};

/**
 * Maps a `location.hash` from the old hash-routed site to a new path.
 * Returns null when the hash is empty or is an in-page anchor (`#install`).
 * Any other `#/…` route that has no entry goes home.
 */
export function resolveHashRedirect(hash: string): string | null {
  if (!hash || hash === "#") return null;
  const raw = hash.startsWith("#") ? hash.slice(1) : hash;
  if (!raw.startsWith("/")) return null;
  const path = raw.split(/[?#]/)[0]!.replace(/^\/+|\/+$/g, "");
  if (path === "") return HASH_ROUTES[""]!;
  const match = /^docs\/([^/]+)$/.exec(path);
  const key = match?.[1];
  return key && Object.hasOwn(HASH_ROUTES, key) ? HASH_ROUTES[key]! : "/";
}

/** Body of `public/_redirects`: real 301s for the path forms of the old routes. */
export function netlifyRedirects(): string {
  const rules = Object.entries(HASH_ROUTES)
    .filter(([slug]) => slug !== "")
    .flatMap(([slug, target]) => [`/docs/${slug}  ${target}  301`, `/docs/${slug}/  ${target}  301`]);
  return [
    "# Old path forms of the hash routes. Generated by scripts/redirects.ts.",
    ...rules,
    "",
    "# The old Netlify address sends every path to the real domain (forced, so it wins over a file).",
    "https://slotsmith-docs.netlify.app/*  https://slotsmith.dev/:splat  301!",
    "",
  ].join("\n");
}
